enable_cache: False
run_name: "dobble-run-1"
settings:
  docker:
    build_context_root: .
    requirements:
      - pillow==9.2.0
      - labelbox[data]==3.27.2
steps:
  ingest_data:
    enable_cache: false
    parameters:
      # Path to image directory containing images
      image_base_dir: "data/dobble/images/"
  prepare_labels:
    enable_cache: false
    parameters:
      # Path to image directory containing images
      image_base_dir: "data/dobble/images/"
      # Path to label directory that will be created
      label_base_dir: "data/dobble/voc"
  split_data:
    enable_cache: false
    parameters:
      # Path to image directory containing images
      image_base_dir: "data/dobble/images/"
      # Path to label directory that will be created
      label_base_dir: "data/dobble/voc"
      # Split ratio to split dataset into trainval and test dataset
      train_test_split_ratio: 0.8
