enable_cache: False
run_name: "dobble-run-1"
settings:
  docker:
    build_context_root: .
    required_integrations: ["pytorch", "mlflow"]
    requirements:
      - opencv-python==4.6.0.66
      - albumentations==1.3.0
      - pascal-voc==0.0.3
      - torchmetrics==0.10.1
      - boto3==1.25.3
      - onnx==1.12.0
      - deepchecks[vision]==0.9.2
      - onnxruntime==1.13.1
      - torchvision==0.13.0
  # Set mlflow experiment to be used by all steps settings here
  experiment_tracker.mlflow:
    experiment_name: "dobble-exp-1"
    nested: False
    # tags: Mapping[str, Any]
steps:
  download_data:
    enable_cache: False
    parameters:
      dataset_base_dir: "data/dobble/voc/"
      service_name: "s3"
      bucket_name: "zenml-data"
  create_data_loader:
    enable_cache: False
    experiment_tracker: mlflow_tracker
    parameters:
      # Path to image directory containing annotations, labels and images
      dataset_base_dir: "data/dobble/voc/"
      # Batch size
      batch_size: 8
      # Whether to use augmentations
      use_aug: True
      # Image size to use for training [300 for fasterrcnn, 320 for ssdlite320]
      image_size: 320
      # Number of workers for multi-process data loading
      num_workers: 4
  validate_data:
    enable_cache: False
    parameters:
      # Select model from ['fasterrcnn_mobilenet_v3_large_fpn', 'fasterrcnn_resnet50_fpn', 'ssdlite320_mobilenet_v3_large']
      net: "ssdlite320_mobilenet_v3_large"
      # If True pretrained backbone + pretrained  detection else pretrained backbone only
      use_pretrained: False
  trainer:
    enable_cache: False
    experiment_tracker: mlflow_tracker
    parameters:
      # Save models folder
      models_folder: "models/"
      # Select model from ['fasterrcnn_mobilenet_v3_large_fpn', 'fasterrcnn_resnet50_fpn', 'ssdlite320_mobilenet_v3_large']
      net: "ssdlite320_mobilenet_v3_large"
      # If True pretrained backbone + pretrained  detection else pretrained backbone only
      use_pretrained: False
      # Learning rate
      lr: 1e-3
      # LR momentum
      momentum: 0.9
      # LR weight decay
      weight_decay: 0.0005
      # T_max value for Cosine Annealing Scheduler
      t_max: 100
      # Number of epochs
      epochs: 100
      # Print frequency
      print_freq: 1
      # Score threshold to filter bounding boxes
      score_threshold: 0.6
      # Save a grid of 3 images (image, ground_truth, predictions) bounding boxes and labels
      save_prediction: True
      # Directory to save images
      prediction_folder: "predictions/"
  validate_data_model:
    enable_cache: False
    experiment_tracker: mlflow_tracker
  export_onnx:
    enable_cache: False
    experiment_tracker: mlflow_tracker
    parameters:
      # Path to save onnx model
      onnx_model_path: "models/model.onnx"
      # Image size to use for training [300 for fasterrcnn, 320 for ssdlite320]
      image_size: 320
