enable_cache: False
run_name: "dobble-run-1"
settings:
  docker:
    build_context_root: .
    requirements:
      pascal-voc==0.0.3
      opencv-python==4.6.0
      albumentations==1.3.0
steps:
  create_data_loader:
    enable_cache: False
    parameters:
      # Path to image directory containing annotations, labels and images
      dataset_base_dir: "data/dobble/voc/"
      # Batch size
      batch_size: 8
      # whether to use augmentations
      use_aug: True
      # image size to use for training
      image_size: 300
      # Number of workers for multi-rpocess data loading
      num_workers: 0
